### ISSUE TITLE
german umlaute

### ISSUE THREAD

**Issue by judos** [gcardone/junidecode#8]
Thanks for the awesome library!
I'm using for transforming names into an appropriate email-address and noted some german umlaute aren't transformed correctly. So I added some additional replacements in my code:
```
		str = str.replace("ä", "ae"); // got "a"
		str = str.replace("Ä", "ae"); // got "a"
		str = str.replace("Ö", "oe"); // got "o"
		str = str.replace("ö", "oe"); // got "o"
		str = str.replace("Ü", "ue"); // got "u"
		str = str.replace("ü", "ue"); // got "u"
		str = str.replace("Ý", "y"); // got "u"
```
Not sure if it is intentional or not. Maybe these mappings only make sense in german and otherwise it's fine. Do you happen to know?

And some special signs for numbers:
```
		str = str.replace("Ø", "0"); // got "o" U+006F : LATIN SMALL LETTER O
		str = str.replace("ø", "0"); // got "o" U+006F : LATIN SMALL LETTER O
```
These seem more clear to me that they should actually get replaced by the number 0.

**Comment by gcardone** [comment]
You are welcome :) All the praise actually goes to the orignal perl library by Sean M. Burke, [text::unidecode](https://metacpan.org/release/Text-Unidecode).

Junidecode behaviour here is consistent with text::unidecode. Quoting Sean's docs:

> In German, there's the typographical convention that an umlaut (the double-dots on: ä ö ü) can be written as an "-e", like with "Schön" becoming "Schoen". But Unidecode doesn't do that-- I have Unidecode simply drop the umlaut accent and give back "Schon".
> 
> I chose this not because I'm a big meanie, but because generally changing "ü" to "ue" is disastrous for all text that's not in German. Finnish "Hyvää päivää" would turn into "Hyvaeae paeivaeae"

I should provide a function to override the default settings, so that if you know that you are dealing mostly with german text, you can override its default behaviour.

For [Ø](https://www.fileformat.info/info/unicode/char/00d8/index.htm) and [ø](http://www.fileformat.info/info/unicode/char/00F8/index.htm) the correct mapping _is_ "O" and "o" because they are letters, not numbers. Using them as "0" is as wrong as using "O" (letter O), so junidecode is doing the right thing here.

I'll try and remember to add character overrides, but feel free to open an issue about it, if you'd like.

I hope this helps.

**Comment by judos** [comment]
Thanks for your reply. It makes sense to me now. I think a character override is not really needed because I can just do it myself before I use the junidecode function to replace the remaining characters.
